/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import demineur.Difficulty;
import demineur.Field;
import demineur.Flag;
import demineur.Land;
import demineur.Mine;
import demineur.Square;
import java.awt.Component;
import java.awt.event.MouseEvent;

/**
 *
 * @author Dimitri
 */
public class Main extends javax.swing.JFrame {
    
    public Field field;
    private Difficulty difficulty;
    private int cleared;
    
    /**
     * Creates new form Main
     */
    public Main() {
        difficulty = Difficulty.MEDIUM;
        cleared = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultyGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        mediumButton = new javax.swing.JRadioButton();
        easyButton = new javax.swing.JRadioButton();
        hardButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        newGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Difficulty :");

        difficultyGroup.add(mediumButton);
        mediumButton.setSelected(true);
        mediumButton.setText("Medium");
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });

        difficultyGroup.add(easyButton);
        easyButton.setText("Easy");
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });

        difficultyGroup.add(hardButton);
        hardButton.setText("Hard");
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(easyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mediumButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newGameButton)
                        .addGap(0, 501, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mediumButton)
                    .addComponent(easyButton)
                    .addComponent(hardButton)
                    .addComponent(newGameButton)))
        );

        jLabel1.getAccessibleContext().setAccessibleName("difficultyLabel");
        mediumButton.getAccessibleContext().setAccessibleName("mediumButton");
        easyButton.getAccessibleContext().setAccessibleName("easyButton");
        hardButton.getAccessibleContext().setAccessibleName("hardButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        difficulty = Difficulty.EASY;
    }//GEN-LAST:event_easyButtonActionPerformed

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        difficulty = Difficulty.MEDIUM;
    }//GEN-LAST:event_mediumButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        difficulty = Difficulty.HARD;
    }//GEN-LAST:event_hardButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        field = new Field(difficulty);
        resetPanel();
        initPanel();
        repaint();
    }//GEN-LAST:event_newGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private void initPanel(){
        SquarePanel panel = null;
        cleared = 0;
        for(int x = 0; x < field.getSetup().getX(); x++){
            for(int y = 0; y < field.getSetup().getY(); y++){
                for(Mine mine : field.getMineField()){
                    if(mine.getX() == x && mine.getY() == y){
                        panel = new SquarePanel(mine);
                        break;
                    }
                    panel = new SquarePanel(new Land(x,y));
                }
                panel.addMouseListener(new java.awt.event.MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        mouseClickedPanel(e);
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                    }
                });
                jPanel1.add(panel);
            }
        }
    }
    
    private void resetPanel() {
        jPanel1.removeAll();
    }
    
    private void loadEndScreen(boolean bool)
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EndFrame ef= new EndFrame();
                if(bool == true)
                    ef.getVictoryLabel().setText("You win !!");
                else 
                    ef.getVictoryLabel().setText("You loose ;(, try again !!");
                ef.setVisible(true);
            }
        });
    };
    
    private void mouseClickedPanel(java.awt.event.MouseEvent evt) {                                           
        SquarePanel panel = ((SquarePanel)evt.getComponent());
        if(evt.getButton() == MouseEvent.BUTTON1){
            if(panel.getSquare().isMine()) {
                if(!panel.getSquare().getFlag().equals(Flag.DISAMORCED)){
                    this.loadEndScreen(false);
                    this.resetPanel();
                }
            }
            else {
                spread(panel.getSquare(), generateSquare());
                if(cleared == this.field.getSetup().getX() * this.field.getSetup().getY() - this.field.getSetup().getMines()){
                    this.loadEndScreen(true);
                    cleared = 0;
                }   
            }
            //resetSpreaded();
        } else {
            panel.getSquare().toggleFlag();
        }
        repaint();
    }  
    
    private void spread(Square square, Square[] squares){
        square.setMines(field.mines(square.getX(), square.getY()));
        square.setFlag(Flag.ISCLEARED);
        if(!square.hasBeenSpreaded())
            cleared ++;
        square.spreaded();
        if(square.getMines() == 0){
           
            for(Square sq : squares){
                if(Math.abs(square.getX() - sq.getX()) <= 1 && Math.abs(square.getY() - sq.getY()) <= 1 && !sq.hasBeenSpreaded()){
                    spread(sq, squares);
                }
            }     
        }
         System.out.println(cleared);
    }
    
    private void resetSpreaded(){
        for(Square sq : generateSquare()){
           sq.resetSpreaded();
        }
    }
    
    private Square[] generateSquare(){
        Component[] components = jPanel1.getComponents(  );
        Square[] squares = new Square[components.length];
        for(int i = 0 ; i < components.length ; i++){
            squares[i] = ((SquarePanel)components[i]).getSquare();
        }  
        return squares;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup difficultyGroup;
    private javax.swing.JRadioButton easyButton;
    private javax.swing.JRadioButton hardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mediumButton;
    private javax.swing.JButton newGameButton;
    // End of variables declaration//GEN-END:variables

    
}
